server:
  port: 7070

spring:
  profiles:
    active: local

  application:
    name: dptestweb

  mvc:
    throw-exception-if-no-handler-found: true

logging:
  config:
    classpath: logback-spring.xml